#cloud-config
autoinstall:
    version: 1
    interactive-sections:
        - identity
        - network
    source:
        id: ubuntu-desktop-minimal

    locale: en_US.UTF-8
    keyboard:
        layout: dk
        variant: ''
    timezone: Europe/Copenhagen

    refresh-installer:
        update: true

    packages:
        - git
        - python3-pip
        - libreoffice

    snaps:
        - name: slack
        channel: stable
        classic: true

        - name: code
        channel: stable
        classic: true

        - name: postman
        channel: stable
        classic: true

    storage:
        layout:
            name: zfs
        config:
      - type: disk
        id: disk0
        ptable: gpt
        path: /dev/nvme0n1
        wipe: superblock-recursive
        preserve: false
        grub_device: true
      - type: partition
        id: partition0
        device: disk0
        size: 512M
        flag: boot
      - type: partition
        id: partition1
        device: disk0
        size: -1
      - type: format
        id: format0
        device: partition0
        fstype: fat32
        label: ESP
      - type: encryption
        id: luks1
        device: partition1
        key: "prompt"
      - type: format
        id: format1
        device: luks1
        fstype: zfs
        label: rpool
      - type: mount
        path: /boot/efi
        device: format0
      - type: zpool
        id: zpool0
        name: rpool
        cachefile: none
        mountpoint: legacy
        devices:
          - luks1
      - type: zfs_dataset
        id: root
        pool: rpool
        mountpoint: /
        name: ROOT

    late-commands:
        - curtin in-target -- apt-get update
            
    
    shutdown: reboot

    


    

    
